services:
  - type: web
    name: Bot-fb
    env: python
    repo: https://github.com/phppho/Bot-fb
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:10000 app:app
    envVars:
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: FACEBOOK_PAGE_ID
        sync: false
      - key: FACEBOOK_ACCESS_TOKEN
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false